server:
  port: 8080
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/duty_management?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root
    password: 123456
    hikari:
      connection-test-query: SELECT 1 # 自动检测连接
      connection-timeout: 60000 #数据库连接超时时间,默认30秒
      idle-timeout: 500000 #空闲连接存活最大时间，默认600000（10分钟）
      max-lifetime: 540000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      maximum-pool-size: 12 #连接池最大连接数，默认是10
      minimum-idle: 10 #最小空闲连接数量
      pool-name: SPHHikariPool # 连接池名称
  mail:
    host: smtp.163.com
    port: 465
    username: yunluhe1@163.com
    password: LB6SQ33E2BpKGXHE
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
myconfig:
  notification:
    email: yunluhe1@163.com
    cronschedule: 0 36 22 * * ?
  salary:
    daysalary: 120







